### ISSUE TITLE
Help appreciated to return back data from program HWTHRCVX to main program

### ISSUE THREAD

**Issue by Thibaut69** [IBM/zOS-Client-Web-Enablement-Toolkit#36]
Hi everybody,

I don't feel at ease with the pointers I guess, and I haven't found the way to get the data back from the RCVX program to the main program, that you have in the sample for POST method : **SYS1.SAMPLIB(HWTHXCB2)**

I can display the data of **ret-data-ptr(J)** in the **Consume-Next-Response-Data** paragraph, but then, I haven't found the way to set the data to the main program.

Can you help me setting correctly this ?

**Comment by ian-burnett** [comment]
In the sample, `recv-callback-udata` is defined in WORKING-STORAGE SECTION. This matches with the `recv-user-data` structure declared In the LINKAGE SECTION of the `HWTHRCVX` callback.

In a program where you wish to save the received data, before starting the connection  you could allocate some storage and save the address of that area in your own pointer field within `recv-callback-udata`. Inside the callback, you can then copy from the `ret-data-ptr(j)` to your storage.

You probably also will need a "maximum capacity" field passing in that user callback area, with associated logic in the callback to prevent buffer overwrites.

If you are saving an offset in the user data structure, use a pointer to a pic 9(8), rather than declaring a pic 9(8) in the userdata itself. If I recall correctly, the callback routine takes a copy at the time of the HWTHSET operation and supplies that copy on every RCVX callback invocation. Updating anything in `recv-user-data` within the callback will not behave as expected.

**Comment by Thibaut69** [comment]
Hello Ian, thanks for your help.

I've found how to get back the data, manipulating pointer and address of field was not my cup of tea haha.

**Comment by ian-burnett** [comment]
That's good news @Thibaut69 - thanks for the feedback.

Agreed about COBOL pointer manipulation - never my first choice! :-)
